---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
  - name: centos-5.10

suites:
  - name: default
    run_list:
      - recipe[analog::default]
    attributes:
